WebApp/Controllers/LanguageController.cs
using EasyTest.Entity;
using EasyTest.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebApp.Helpers;
using WebApp.Models;
using WevApp.Helpers;

namespace WebApp.Controllers
{
    public class LanguageController : BaseController
    {
        public ActionResult GetSupportLanguage()
        {
            var lanquage = GetSupportedLanguages();
            return PartialView(lanquage);
        }

        [NonAction]
        public List<String> GetAllCultureCode()
        {

            return _lanquageService.GetAllLanguageCode();
        }

        RouteData routeData;

        public ActionResult SetCulture(String culture)
        {
            culture = CultureHelper.GetImplementedCulture(culture);
            ChangeRouteCulture(culture);
            return RedirectToRoute(routeData.Values);
        }

        private void ChangeRouteCulture(string culture)
        {          
            var fullUrl = Request.UrlReferrer.ToString();
            var questionMarkIndex = fullUrl.IndexOf('?');
            string queryString = null;
            string url = fullUrl;
            if (questionMarkIndex != -1) // There is a QueryString
            {
                url = fullUrl.Substring(0, questionMarkIndex);
                queryString = fullUrl.Substring(questionMarkIndex + 1);
            }

            // Arranges
            var request = new HttpRequest(null, url, queryString);
            var response = new HttpResponse(new System.IO.StringWriter());
            var httpContext = new HttpContext(request, response);

            routeData = System.Web.Routing.RouteTable.Routes.GetRouteData(new HttpContextWrapper(httpContext));

            routeData.Values["culture"] = culture;
        }
    }
}

WebApp/Controllers/NewsCategoryController.cs
using EasyTest.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class NewsCategoryController : Controller
    {

        private readonly INewsCategoryService _newsCategoryService;

        public NewsCategoryController(INewsCategoryService service)
        {
            _newsCategoryService = service;
        }

        [ChildActionOnly]
        public ActionResult Index()
        {
            var vm = _newsCategoryService.GetCategoriesMenu();

            return PartialView(vm);
        }
    }
}

WebApp/Controllers/ReleaseController.cs
using EasyTest.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class ReleaseController : BaseController
    {
        private readonly IAppService _appService; 

        public ReleaseController(IAppService appService)
        {
            _appService = appService;
        }

    

        public ActionResult All(Int32 page=1)
        {
            PageSize = 5;

            var apps = _appService.GetAll(langID).OrderBy(x=>x.Entity.TimeCreated);

            return View(apps.ToPagedList(page, PageSize));
        }

      
        public ActionResult Show(Int32? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var vm = _appService.FindById(id,langID);

            if (vm == null)
            {
                return HttpNotFound();
            }


            return View(vm);
        }

    }
}

WebApp/Areas/AdminAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>@ViewBag.Title</title>
	<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
	<!-- Bootstrap 3.3.2 -->
	@Styles.Render("~/Content/admin")
	<!-- Ionicons -->
	<link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
	<!-- Theme style -->
	<link href="~/Content/css/admin/AdminLTE.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/css/admin/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
	@RenderSection("style", required: false)
</head>
<body class="skin-yellow">


	<div class="wrapper">
		<!-- Main Header -->
		<header class="main-header">
			<!-- Logo -->
			<a href="@Url.Action("Index","Admin")" class="logo">EasyTest</a>
			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- Messages: style can be found in dropdown.less-->
						<li class="dropdown messages-menu">
							<!-- Menu toggle button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-envelope-o"></i>
								<span class="label label-success">4</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 4 messages</li>
								<li>
									<!-- inner menu: contains the messages -->
									<ul class="menu">
										<li>
											<!-- start message -->
											<a href="#">
												<div class="pull-left">
													<!-- User Image -->
													<img src="~/Content/Images/admin/user1-128x128.jpg" class="img-circle" alt="User Image" />
												</div>
												<!-- Message title and timestamp -->
												<h4>
													Support Team
													<small><i class="fa fa-clock-o"></i> 5 mins</small>
												</h4>
												<!-- The message -->
												<p>Why not buy a new awesome theme?</p>
											</a>
										</li><!-- end message -->
									</ul><!-- /.menu -->
								</li>
								<li class="footer"><a href="#">See All Messages</a></li>
							</ul>
						</li><!-- /.messages-menu -->
						<!-- Notifications Menu -->
						<li class="dropdown notifications-menu">
							<!-- Menu toggle button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-bell-o"></i>
								<span class="label label-warning">10</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 10 notifications</li>
								<li>
									<!-- Inner Menu: contains the notifications -->
									<ul class="menu">
										<li>
											<!-- start notification -->
											<a href="#">
												<i class="fa fa-users text-aqua"></i> 5 new members joined today
											</a>
										</li><!-- end notification -->
									</ul>
								</li>
								<li class="footer"><a href="#">View all</a></li>
							</ul>
						</li>
						<!-- Tasks Menu -->
						<li class="dropdown tasks-menu">
							<!-- Menu Toggle Button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-flag-o"></i>
								<span class="label label-danger">9</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 9 tasks</li>
								<li>
									<!-- Inner menu: contains the tasks -->
									<ul class="menu">
										<li>
											<!-- Task item -->
											<a href="#">
												<!-- Task title and progress text -->
												<h3>
													Design some buttons
													<small class="pull-right">20%</small>
												</h3>
												<!-- The progress bar -->
												<div class="progress xs">
													<!-- Change the css width attribute to simulate progress -->
													<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
														<span class="sr-only">20% Complete</span>
													</div>
												</div>
											</a>
										</li><!-- end task item -->
									</ul>
								</li>
								<li class="footer">
									<a href="#">View all tasks</a>
								</li>
							</ul>
						</li>
						<!-- User Account Menu -->
						<li class="dropdown user user-menu">
							<!-- Menu Toggle Button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<!-- The user image in the navbar-->
								<img src="~/Content/Images/admin/user2-160x160.jpg" class="user-image" alt="User Image" />
								<!-- hidden-xs hides the username on small devices so only the image appears. -->
								<span class="hidden-xs"> @ViewBag.Username</span>
							</a>
							<ul class="dropdown-menu">
								<!-- The user image in the menu -->
								<li class="user-header">
									<img src="~/Content/Images/admin/user2-160x160.jpg" class="img-circle" alt="User Image" />
									<p>
										 @ViewBag.Username - Web Developer
										<small>Member since Nov. 2012</small>
									</p>
								</li>
								<!-- Menu Body -->
								<li class="user-body">
									<div class="col-xs-4 text-center">
										<a href="#">Followers</a>
									</div>
									<div class="col-xs-4 text-center">
										<a href="#">Sales</a>
									</div>
									<div class="col-xs-4 text-center">
										<a href="#">Friends</a>
									</div>
								</li>
								<!-- Menu Footer-->
								<li class="user-footer">
									<div class="pull-left">
										<a href="#" class="btn btn-default btn-flat">Profile</a>
									</div>
									<div class="pull-right">

										
                                        @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.Hidden("returnUrl", "/AdminAuth");
    <a class="btn btn-default btn-flat" style="float:right;margin-top:30px;" href="javascript:document.getElementById('logoutForm').submit()"><span class="glyphicon glyphicon-log-out">&nbsp</span>[Вийти]</a>
                                        }


									</div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>
		</header>
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">
			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">
				<!-- Sidebar user panel (optional) -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="~/Content/Images/admin/user2-160x160.jpg" class="img-circle" alt="User Image" />
					</div>
					<div class="pull-left info">
						<p> @ViewBag.Username</p>
						<!-- Status -->
						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>
				<!-- search form (Optional) -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Search..." />
						<span class="input-group-btn">
							<button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				<!-- Sidebar Menu -->
				<ul class="sidebar-menu">
					<li class="header">HEADER</li>
					<!-- Optionally, you can add icons to the links -->
					<li class="active"><a href="#"><span>Сторінки</span></a><</li>
					<li><a href="@Url.Action("Index","Release")"><span>Релізи</span></a></li>

					<li class="treeview">
						<a href="@Url.Action("Index","News")"><span>[Новини]</span> <i class="fa fa-angle-left pull-right"></i></a>
						<ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","News")">[Переглянути]</a></li>
							<li><a href="@Url.Action("Create","News")">Додати</a></li>
							<li><a href="@Url.Action("Index","NewsCategory")">Категорії</a></li>
						</ul>
					</li>
                    <li><a href="@Url.Action("Index","Page")"><span>[Сторінки]</span></a></li>
                    <li><a href="#"><span>Повідомлення</span></a></li>

					<li><a href="#"><span>Повідомлення</span></a></li>
					<li><a href="@Url.Action("Index","FeedbackSubject")"><span>Повідомлення|Категорії</span></a></li>
					<li><a href="#"><span>Тести</span></a></li>
				
					<li><a href="@Url.Action("Index","University")">Університети</a></li>
                   
				</ul><!-- /.sidebar-menu -->
            
			</section>
			<!-- /.sidebar -->
		</aside>
		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
                    @ViewBag.Title
				</h1>
				<ol class="breadcrumb">
					<li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
					<li class="active">Here</li>
				</ol>
			</section>
			<!-- Main content -->
			<section class="content">
				@RenderBody()
				<!-- Your Page Content Here -->
			</section><!-- /.content -->
		</div><!-- /.content-wrapper -->
		<!-- Main Footer -->
		<footer class="main-footer">
			<!-- To the right -->
			<div class="pull-right hidden-xs">
				Anything you want
			</div>
			<!-- Default to the left -->
			<strong>Copyright &copy; @DateTime.Now.Year <a href="#">EasyTest</a>.</strong> All rights reserved.
		</footer>
	</div><!-- ./wrapper -->


	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	<script src="~/Scripts/app.js" type="text/javascript"></script>
	<script src="~/Scripts/admin/demo.js" type="text/javascript"></script>

	@RenderSection("scripts", required: false)


</body>
</html>

WebApp/Areas/AdminAuth/Views/Shared/_language.cshtml
@model   IEnumerable<EasyTest.Entity.Language>

@{
    var name = ViewData["name"].ToString();
    var pref = ViewData["pref"].ToString();
    var selected = (Int32)ViewData["selected"];
}

<select class="Language@(pref)" name="@(name)" size="1" style="width:140px;">
    @foreach (var lang in Model)
    {
        <option value='@lang.ID'
                data-image="@Url.Content("~/Content/Images/blank.gif")"
                data-imagecss="flag   @lang.Icon"
                data-title="@lang.NativeName"
                @if (selected == lang.ID)
                { <text> selected="selected" </text>       }
                }>
            @lang.NativeName
        </option>
    }
</select>