WebApp/Controllers/CaptchaController.cs
using System;
using System.Drawing;
using System.IO;
using System.Net;
using System.Web.Mvc;
using WebApp.Helpers;

namespace WebApp.Controllers
{
    public class CaptchaController : Controller
    {
        
        public ActionResult ShowCaptcha()
        {
            return PartialView("_Captcha");

        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public FileContentResult CaptchaImage()
        {
        
            if (Session["request"] != null)
            {
                Session.Remove("request");
            }

            var memStream = new MemoryStream();
            Int32 res;
            String text = CaptchaHelper.GetCaptcha(out res);

            Session["Captcha"] = res;//Запис результату в сесію

            FileContentResult img = null;

            //Generate an image from the text stored in session
            Bitmap imgCapthca = CaptchaHelper.GenerateImage(180, 30, text);

            imgCapthca.Save(memStream, System.Drawing.Imaging.ImageFormat.Jpeg);

            byte[] imgBytes = memStream.GetBuffer();
            imgCapthca.Dispose();
            memStream.Close();
            img = this.File(memStream.GetBuffer(), "image/Jpeg");
            return img;
        }

      
        [HttpPost]
        public ActionResult HelpMe()
        {
            if (Session["request"] != null && (Boolean)Session["request"] == true)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session["request"] = true;
            Int32 value = (Int32)Session["Captcha"];
           
            var helpList =   CaptchaHelper.HelpMe(value);
           
            return Json(helpList);
        }
    }
}

WebApp/Controllers/FeedbackController.cs
using EasyTest.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class FeedbackController : BaseController
    {
        // GET: Feedback
        public ActionResult Index()
        {
            SubjectDropDownList();
            return View();
        }
        private void SubjectDropDownList()
        {

            var subject = _unitOfWorkAsync.Repository<FeedbackCategory>().Queryable();
            ViewBag.Subject = subject;
        }

    }
}

WebApp/Controllers/LanguageController.cs
using EasyTest.Entity;
using EasyTest.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using WebApp.Helpers;
using WebApp.Models;
using WevApp.Helpers;

namespace WebApp.Controllers
{
    public class LanguageController : BaseController
    {
        public ActionResult GetSupportLanguage()
        {
            var lanquage = GetSupportedLanguages();
            return PartialView(lanquage);
        }

        [NonAction]
        public List<String> GetAllCultureCode()
        {

            return _lanquageService.GetAllLanguageCode();
        }

        RouteData routeData;

        public ActionResult SetCulture(String culture)
        {
            culture = CultureHelper.GetImplementedCulture(culture);
            ChangeRouteCulture(culture);
            return RedirectToRoute(routeData.Values);
        }

        private void ChangeRouteCulture(string culture)
        {          
            var fullUrl = Request.UrlReferrer.ToString();
            var questionMarkIndex = fullUrl.IndexOf('?');
            string queryString = null;
            string url = fullUrl;
            if (questionMarkIndex != -1) // There is a QueryString
            {
                url = fullUrl.Substring(0, questionMarkIndex);
                queryString = fullUrl.Substring(questionMarkIndex + 1);
            }

            // Arranges
            var request = new HttpRequest(null, url, queryString);
            var response = new HttpResponse(new System.IO.StringWriter());
            var httpContext = new HttpContext(request, response);

            routeData = System.Web.Routing.RouteTable.Routes.GetRouteData(new HttpContextWrapper(httpContext));

            routeData.Values["culture"] = culture;
        }
    }
}

WebApp/Controllers/ReleaseController.cs
using EasyTest.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class ReleaseController : BaseController
    {
        private readonly IAppService _appService; 

        public ReleaseController(IAppService appService)
        {
            _appService = appService;
        }

    

        public ActionResult All(Int32 page=1)
        {
            PageSize = 5;

            var apps = _appService.GetAll(langID).OrderBy(x=>x.Entity.TimeCreated);

            return View(apps.ToPagedList(page, PageSize));
        }

      
        public ActionResult Show(Int32? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var vm = _appService.FindById(id,langID);

            if (vm == null)
            {
                return HttpNotFound();
            }


            return View(vm);
        }

    }
}

WebApp/Views/Shared/_Captcha.cshtml
@model WebApp.Models.CaptchaModel
<div id="CaptchaContainer">
    <div class="row">
        <div class="col-md-6">
            @Html.Bootstrap().LabelFor(model => model.CaptchaAnswer).Class("control-label col-md-3")
            <div class="col-md-9">
                <img src="@Url.Action("CaptchaImage","Captcha")" id="captchaImage" alt="Captcha" />

                <a href="@Url.Action("CaptchaImage", "Captcha")" id="refreshCaptcha"><i class="fa fa-refresh"></i></a>
                <i class="fa fa-spinner fa-pulse loading" style="display:none"></i>
                <a href="@Url.Action("HelpMe","Captcha")" id="captchaHelp"><i class="fa fa-question"></i></a>
                <div id="captchaAnswers"></div>
            </div>
        </div>
        <div class="col-md-6">
            <label for="captcha" class="control-label col-md-3"> [Ввести відповідь]</label>
            <div class="col-md-9">
                @Html.TextBoxFor(model => model.CaptchaAnswer, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.CaptchaAnswer)
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@CultureHelper.GetCurrentNeutralCulture()" dir="@(CultureHelper.IsRighToLeft() ? "rtl" : "ltr")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <noscript>
        <meta http-equiv="Refresh" content="0;URL=@Url.Action("JSDisabled","Home")">
    </noscript>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("style", required: false)
</head>
<body>
    @*<script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-54632626-1', 'auto');
            ga('send', 'pageview');
        </script>*@
    <div class="page-wrap">
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">

                    <div class="col-sm-12">


		<a href="@Url.Action("Login","Account",new {returnUrl="WebInterface"})"  id="LogIn" >
			<span class="hidden-xs">Web interface</span>
		</a>

        <a href="@Url.Action("Register","Account")">[Реєстрація]</a>
						

                        <div class="social-icons pull-right">
							
						
                            @Html.Action("GetSupportLanguage", "Language")
                            <ul class="nav navbar-nav">
                                <li>
                                    <a href="https://www.facebook.com/groups/easytest.com.ua/" target="_blank"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/EasyTest_" target="_blank"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/EasyTest_" target="_blank"><i class="fa fa-google-plus"></i> </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("RSS","News")" target="_blank"><i class="fa fa-rss"></i> </a>
                                </li>
							
</ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-middle" id="menu">
            
            <!--header-middle-->
            <div class="container">
                <div class="row">           
                    <div class="col-sm-4">
                        <div class="logo" style="display:none">
                            <a href="@Url.Action("Index","Home")" title="Easytest.com.ua">
                                <img src="~/Content/Images/logo.png" height="100" alt="EasyTest">
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-8">
                        <div class="top-menu pull-right">
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink(Resource.GlobalRes.Download, "All", "Release")</li>
                                <li> @Html.ActionLink("Документація", "", "")</li>
                                <li> @Html.ActionLink(Resource.GlobalRes.News, "All", "News")</li>
                                <li> @Html.ActionLink(Resource.GlobalRes.Feedback, "Index", "Feedback") </li>
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>




        <div class="container-fluid" id="section">
            <div class="main-body">
                @RenderBody()
                </div>
        </div>
    </div>

    <div id="footer">
        <div class="container">
            <div class="row">

                <article class="col-xs-12 col-sm-12 col-md-4 col-lg-4 about">
                    <h3>@Resource.GlobalRes.AboutEasyTest</h3>

                    @{Html.RenderAction("About", "Home");}


         

                </article>
                <article class="col-xs-5 col-sm-6 col-md-4  col-lg-4">
                    <h3>@Resource.GlobalRes.EthernetLinks</h3>
                    <ul class="nav mediaInfo">
                        <li>
                            <a href="https://www.facebook.com/groups/easytest.com.ua/" target=" _blank" title="Ми на Facebook">
                                <img src="~/Content/Images/FB-logo.png" alt="Facebook-group" />
                                Facebook
                            </a>
                        </li>
                        <li>
                            <a href="https://www.google.com/+EasytestUa" rel="publisher" target="_blank" style="text-decoration:none;">
                                <img src="~/Content/Images/google_plus_icon.png" title="Сторінка в Google+" alt="Google+" style="border:0;width:32px;height:32px;" />
                                Google+
                            </a>
                        </li>

                        <li>
                            <a href="https://twitter.com/EasyTest_" rel="publisher" target="_blank" style="text-decoration:none;">
                                <img src="~/Content/Images/twitter_icon.png" title="Сторінка в Twitter" alt="Twitter" style="border:0;width:32px;height:32px;" />
                                Twitter
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("RSS","News")" target="_blank">
                                <img src="~/Content/Images/rss.png" title="RSS EasyTest" alt="RSS" style="border:0;width:32px;height:32px;" />
                                RSS
                            </a>
                        </li>


                    </ul>
                </article>
                <article class="col-xs-7 col-sm-6 col-md-4  col-lg-4">
                    <h3>@Resource.GlobalRes.YouContact</h3>
                    <ul class="nav mediaInfo contactInfo">
                        <li>

                            <a href="https://facebook.com/krasnytsia" target="_blank">
                                <img src="~/Content/Images/icontexto-user-web20-facebook_4996.png" alt="Author" title="Автор" />
                                Тарас Красниця
                            </a>

                        </li>
                        <li>
                            <div>
                                <img src="~/Content/Images/phone_7533.png" alt="Моб." title="Автор" />
                                +380660466668
                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="~/Content/Images/contact_7840.png" alt="Моб." title="Email" />
                                <script type="text/javascript">

                                    function gen_mail_to_link(lhs, rhs, subject) {

                                        document.write("<a href=\"mailto");
                                        document.write(":" + lhs + "&#64;");
                                        document.write(rhs + "?subject=" + subject + "\">" + lhs + "&#64;" + rhs + "<\/a>");

                                    };
                                    gen_mail_to_link('Rocket2602', 'gmail.com', 'Feedback about your site...');
                                </script>
                                <noscript>
                                    <em>Email address protected by JavaScript. Activate javascript to see the email.</em>
                                </noscript>


                            </div>
                        </li>
                        <li>
                            <div>
                                <img src="~/Content/Images/skype_1688.png" alt="Author" title="Skype" />
                                Rocket260264
                            </div>
                        </li>

                    </ul>

                </article>
            </div>
            <div class="row">
                <hr />
                <div class="copyright">
                    Copyright  &#169; 2014 @if (@DateTime.Now.Year > 2014)
                    {<text>- </text>@DateTime.Now.Year}. @Resource.GlobalRes.AllLawProtected
                </div>
            </div>
        </div>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.dd.js")"></script>

    <script type="text/javascript">
        $(function () {
            $('#Countries').msDropDown();
          

            $('#Countries').change(function () {

                $("#SelectLangForm").submit();
            });



            


            $("#LogIn").click(function (e) {
            	e.preventDefault();

            	var dialog = BootstrapDialog.show({
            	    title: '[Авторизація]',
            	    message: $('<div id="LoginModal"></div>').load($(this).attr("href"))
            	});
	
            });


        })
    </script>
    @RenderSection("scripts", required: false)

	
    @*<script type="text/javascript">
            cackle_widget = window.cackle_widget || [];
            cackle_widget.push({ widget: 'CommentCount', id: 30435 });
            (function () {
                var mc = document.createElement('script');
                mc.type = 'text/javascript';
                mc.async = true;
                mc.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cackle.me/widget.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mc, s.nextSibling);
            })();
        </script>*@
</body>
</html>

WebApp/Views/Shared/_SelectCountries.cshtml
@model IQueryable<EasyTest.Entity.Country>

@helper selected(Int32 selectedID, Int32 itemID)
{
		if (selectedID == itemID)
		{
				@:selected="selected"
		}
}

<select name="CountryID" id="CountryID" style="width:100%;">

	@{
        Boolean IsSelect = false;
        Int32 selectedID=-1;

        if (ViewData["selectedID"]!=null && ViewData["selectedID"] is Int32)
        {
            IsSelect = true;
            selectedID = (Int32)ViewData["selectedID"];
        }
	}

    
	@foreach (var item in Model)
	{
		<option value='@item.ID'
				data-image="@Url.Content("~/Content/Images/blank.gif")"
				data-imagecss="flag @item.Icon"
				data-title="@item.Name"
				@if (IsSelect) {@selected(selectedID, item.ID); }
				>
			@Resource.Extend.GetString(item.Name)
		</option>
}
</select>